#!/bin/bash

# Define the input file
input_file="ips.txt"

# Read each IP address from the input file
while IFS= read -r ip
do
    # Check if the line is not empty
    if [ -n "$ip" ]; then
        # Replace special characters in IP address to create a valid filename
        safe_ip=$(echo "$ip" | sed 's/[^0-9.]//g')
        output_file="${safe_ip}_sslscan_results.txt"
        
        echo "Scanning $ip..." > "$output_file"
        # Run sslscan and write the results to the corresponding output file
        sslscan "$ip" >> "$output_file"
        echo "Scan complete for $ip. Results are in $output_file."
    fi
done < "$input_file"
